/**
 * Lightweight CodeMUX model registry — curated display names (Cherry-aligned).
 *
 * Maintain `MODEL_CATALOG` / `PROVIDER_MODEL_OVERRIDES` here directly.
 * Provider id notes: siliconflow ≈ Cherry `silicon`, opencode-go ≈ Cherry `opencode`.
 */

export type CatalogModel = {
  id: string;
  name: string;
};

export type ProviderModelOverride = {
  /** Builtin template id (`anthropic`, `openrouter`, …). */
  providerId: string;
  /** Canonical catalog model id. */
  modelId: string;
  /** Wire id when it differs from `modelId`. Defaults to `modelId`. */
  apiModelId?: string;
  /** Provider-specific display name override (Cherry override.name). */
  name?: string;
};

/** Global curated models (exact / fuzzy id match). */
export const MODEL_CATALOG: readonly CatalogModel[] = [
  { id: "aion-2-0", name: "Aion-2.0" },
  { id: "aion-3-0", name: "Aion-3.0" },
  { id: "aion-3-0-mini", name: "Aion-3.0-Mini" },
  { id: "aion-rp-llama-3-1-8b", name: "Aion-RP 1.0 (8B)" },
  { id: "chatgpt-image-latest", name: "chatgpt-image-latest" },
  { id: "claude-3-haiku", name: "Claude Haiku 3" },
  { id: "claude-fable-5", name: "Claude Fable 5" },
  { id: "claude-fable-latest", name: "Anthropic: Claude Fable Latest" },
  { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
  { id: "claude-haiku-latest", name: "Anthropic Claude Haiku Latest" },
  { id: "claude-opus-4", name: "Claude Opus 4" },
  { id: "claude-opus-4-1", name: "Claude Opus 4.1" },
  { id: "claude-opus-4-5", name: "Claude Opus 4.5" },
  { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
  { id: "claude-opus-4-6-v1", name: "Claude Opus 4.6" },
  { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
  { id: "claude-opus-4-7-fast", name: "Anthropic: Claude Opus 4.7 (Fast)" },
  { id: "claude-opus-4-8", name: "Claude Opus 4.8" },
  { id: "claude-opus-4-8-fast", name: "Claude Opus 4.8 (Fast)" },
  { id: "claude-opus-5", name: "Claude Opus 5" },
  { id: "claude-opus-5-fast", name: "Claude Opus 5 (Fast)" },
  { id: "claude-opus-latest", name: "Anthropic: Claude Opus Latest" },
  { id: "claude-sonnet-4", name: "Claude Sonnet 4" },
  { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5" },
  { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
  { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
  { id: "claude-sonnet-latest", name: "Anthropic Claude Sonnet Latest" },
  { id: "codestral", name: "Codestral (latest)" },
  { id: "cogito-v2-1-671b", name: "Deep Cogito: Cogito v2.1 671B" },
  { id: "cogview-4", name: "cogview-4" },
  { id: "command-a", name: "Command A" },
  { id: "command-r-08-2024", name: "Command R (08-2024)" },
  { id: "command-r-plus-08-2024", name: "Command R+ (08-2024)" },
  { id: "command-r7b-12-2024", name: "Command R7B" },
  { id: "cydonia-24b-v4-1", name: "Cydonia 24B V4.1" },
  { id: "dall-e-2", name: "Dall E 2" },
  { id: "dall-e-3", name: "DALL-E-3" },
  { id: "deepseek-chat", name: "DeepSeek Chat" },
  { id: "deepseek-chat-v3", name: "DeepSeek: DeepSeek V3 0324" },
  { id: "deepseek-chat-v3-1", name: "DeepSeek: DeepSeek V3.1" },
  { id: "deepseek-r1", name: "DeepSeek-R1" },
  { id: "deepseek-r1-distill-llama-70b", name: "DeepSeek R1 Distill Llama 70B" },
  { id: "deepseek-r1-distill-llama-8b", name: "DeepSeek R1 Distill Llama 8B" },
  { id: "deepseek-r1-distill-qwen-1-5b", name: "DeepSeek R1 Distill Qwen 1.5B" },
  { id: "deepseek-r1-distill-qwen-14b", name: "DeepSeek R1 Distill Qwen 14B" },
  { id: "deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B" },
  { id: "deepseek-r1-distill-qwen-7b", name: "DeepSeek R1 Distill Qwen 7B" },
  { id: "deepseek-reasoner", name: "DeepSeek Reasoner" },
  { id: "deepseek-v3", name: "DeepSeek V3 0324" },
  { id: "deepseek-v3-1", name: "DeepSeek-V3.1" },
  { id: "deepseek-v3-1-maas", name: "DeepSeek V3.1" },
  { id: "deepseek-v3-1-terminus", name: "DeepSeek V3.1 Terminus" },
  { id: "deepseek-v3-2", name: "DeepSeek V3.2 Thinking" },
  { id: "deepseek-v3-2-exp", name: "DeepSeek V3.2 Exp" },
  { id: "deepseek-v3-2-maas", name: "DeepSeek V3.2" },
  { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
  { id: "deepseek-v4-flash-latest", name: "DeepSeek V4 Flash Latest" },
  { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
  { id: "dolphin-mistral-24b-venice-edition", name: "Uncensored" },
  { id: "embedding-3", name: "Embedding-3" },
  { id: "ernie-4-5-300b-a47b", name: "baidu/ERNIE-4.5-300B-A47B" },
  { id: "ernie-4-5-vl-424b-a47b", name: "Baidu: ERNIE 4.5 VL 424B A47B" },
  { id: "flux-2-flex", name: "Flux 2 Flex" },
  { id: "flux-2-klein-4b", name: "FLUX.2 Klein 4B" },
  { id: "flux-2-max", name: "FLUX.2 [max]" },
  { id: "flux-2-pro", name: "Flux 2 Pro" },
  { id: "free", name: "Free Models Router" },
  { id: "fugu-ultra", name: "Fugu Ultra" },
  { id: "gemini-2-5-flash", name: "Gemini 2.5 Flash" },
  { id: "gemini-2-5-flash-image", name: "gemini-2.5-flash-image" },
  { id: "gemini-2-5-flash-lite", name: "Gemini 2.5 Flash-Lite" },
  { id: "gemini-2-5-pro", name: "Gemini 2.5 Pro" },
  { id: "gemini-2-5-pro-preview", name: "Google: Gemini 2.5 Pro Preview 06-05" },
  { id: "gemini-2-5-pro-preview-05-06", name: "Google: Gemini 2.5 Pro Preview 05-06" },
  { id: "gemini-3-1-flash-image", name: "Nano Banana 2" },
  { id: "gemini-3-1-flash-image-preview", name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)" },
  { id: "gemini-3-1-flash-lite", name: "Gemini 3.1 Flash Lite" },
  { id: "gemini-3-1-flash-lite-image", name: "Nano Banana 2 Lite" },
  { id: "gemini-3-1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
  { id: "gemini-3-1-pro-preview", name: "Gemini 3.1 Pro Preview" },
  { id: "gemini-3-1-pro-preview-customtools", name: "Gemini 3.1 Pro Preview Custom Tools" },
  { id: "gemini-3-5-flash", name: "Gemini 3.5 Flash" },
  { id: "gemini-3-5-flash-lite", name: "Gemini 3.5 Flash Lite" },
  { id: "gemini-3-6-flash", name: "Gemini 3.6 Flash" },
  { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
  { id: "gemini-3-pro-image", name: "Nano Banana Pro (Gemini 3 Pro Image)" },
  { id: "gemini-3-pro-image-preview", name: "gemini-3-pro-image-preview" },
  { id: "gemini-flash-latest", name: "Gemini Flash Latest" },
  { id: "gemini-pro-latest", name: "Google Gemini Pro Latest" },
  { id: "gemma-2-27b-it", name: "Google: Gemma 2 27B" },
  { id: "gemma-3-12b-it", name: "Gemma 3 12B IT" },
  { id: "gemma-3-27b-it", name: "Google Gemma 3 27B Instruct" },
  { id: "gemma-3-4b-it", name: "Gemma 3 4B IT" },
  { id: "gemma-3n-e4b-it", name: "Gemma 3n E4b It" },
  { id: "gemma-4-26b-a4b-it", name: "Gemma 4 26B A4B IT" },
  { id: "gemma-4-31b-it", name: "Gemma-4-31B-IT" },
  { id: "glm-3-turbo", name: "GLM-3-Turbo" },
  { id: "glm-4", name: "GLM-4" },
  { id: "glm-4-1v", name: "GLM-4.1V-Thinking" },
  { id: "glm-4-5", name: "GLM-4.5" },
  { id: "glm-4-5-air", name: "GLM-4.5-Air" },
  { id: "glm-4-5-flash", name: "GLM-4.5-Flash" },
  { id: "glm-4-5v", name: "GLM-4.5V" },
  { id: "glm-4-6", name: "GLM-4.6" },
  { id: "glm-4-6v", name: "GLM-4.6V" },
  { id: "glm-4-6v-flash", name: "GLM-4.6V-Flash" },
  { id: "glm-4-7", name: "GLM-4.7" },
  { id: "glm-4-7-flash", name: "GLM-4.7-Flash" },
  { id: "glm-4-7-flashx", name: "GLM-4.7-FlashX" },
  { id: "glm-4-7-maas", name: "GLM-4.7" },
  { id: "glm-4-air", name: "GLM-4-Air" },
  { id: "glm-4-airx", name: "GLM-4-AirX" },
  { id: "glm-4-flash", name: "GLM-4-Flash" },
  { id: "glm-4-flashx", name: "GLM-4-FlashX" },
  { id: "glm-4-long", name: "GLM-4-Long" },
  { id: "glm-4-plus", name: "GLM-4-Plus" },
  { id: "glm-4v", name: "GLM-4V" },
  { id: "glm-4v-flash", name: "GLM-4V-Flash" },
  { id: "glm-4v-plus", name: "GLM-4V-Plus" },
  { id: "glm-5", name: "GLM-5" },
  { id: "glm-5-1", name: "GLM-5.1" },
  { id: "glm-5-2", name: "GLM-5.2" },
  { id: "glm-5-2-fast", name: "GLM 5.2 Fast" },
  { id: "glm-5-maas", name: "GLM-5" },
  { id: "glm-5-turbo", name: "GLM 5 Turbo" },
  { id: "glm-5v-turbo", name: "GLM-5V-Turbo" },
  { id: "glm-image", name: "glm-image" },
  { id: "glm-z1", name: "GLM-Z1" },
  { id: "glm-z1-air", name: "GLM-Z1-Air" },
  { id: "glm-z1-airx", name: "GLM-Z1-AirX" },
  { id: "glm-z1-flash", name: "GLM-Z1-Flash" },
  { id: "gpt-3-5-turbo", name: "GPT-3.5 Turbo" },
  { id: "gpt-3-5-turbo-16k", name: "OpenAI: GPT-3.5 Turbo 16k" },
  { id: "gpt-3-5-turbo-instruct", name: "OpenAI: GPT-3.5 Turbo Instruct" },
  { id: "gpt-4", name: "GPT-4" },
  { id: "gpt-4-1", name: "GPT-4.1" },
  { id: "gpt-4-1-mini", name: "GPT-4.1 mini" },
  { id: "gpt-4-1-nano", name: "GPT-4.1 nano" },
  { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
  { id: "gpt-4-turbo-preview", name: "OpenAI: GPT-4 Turbo Preview" },
  { id: "gpt-4o", name: "GPT-4o" },
  { id: "gpt-4o-mini", name: "GPT-4o mini" },
  { id: "gpt-4o-mini-search-preview", name: "GPT 4o Mini Search Preview" },
  { id: "gpt-4o-mini-transcribe", name: "GPT-4o mini Transcribe" },
  { id: "gpt-4o-transcribe", name: "GPT-4o Transcribe" },
  { id: "gpt-5", name: "GPT-5" },
  { id: "gpt-5-1", name: "GPT 5.1 Thinking" },
  { id: "gpt-5-1-codex", name: "GPT-5.1-Codex" },
  { id: "gpt-5-1-codex-max", name: "GPT 5.1 Codex Max" },
  { id: "gpt-5-1-codex-mini", name: "GPT-5.1 Codex mini" },
  { id: "gpt-5-1-instant", name: "GPT-5.1 Instant" },
  { id: "gpt-5-2", name: "GPT-5.2" },
  { id: "gpt-5-2-chat", name: "OpenAI: GPT-5.2 Chat" },
  { id: "gpt-5-2-chat-latest", name: "GPT-5.2 Chat" },
  { id: "gpt-5-2-codex", name: "GPT-5.2-Codex" },
  { id: "gpt-5-2-pro", name: "GPT 5.2" },
  { id: "gpt-5-3-chat", name: "GPT-5.3 Chat" },
  { id: "gpt-5-3-chat-latest", name: "GPT-5.3 Chat (latest)" },
  { id: "gpt-5-3-codex", name: "GPT 5.3 Codex" },
  { id: "gpt-5-3-codex-spark", name: "GPT-5.3 Codex Spark" },
  { id: "gpt-5-4", name: "GPT-5.4" },
  { id: "gpt-5-4-image-2", name: "OpenAI: GPT-5.4 Image 2" },
  { id: "gpt-5-4-mini", name: "GPT 5.4 Mini" },
  { id: "gpt-5-4-nano", name: "GPT 5.4 Nano" },
  { id: "gpt-5-4-pro", name: "GPT 5.4 Pro" },
  { id: "gpt-5-5", name: "GPT-5.5" },
  { id: "gpt-5-5-pro", name: "GPT 5.5 Pro" },
  { id: "gpt-5-6", name: "GPT-5.6" },
  { id: "gpt-5-6-luna", name: "GPT-5.6 Luna" },
  { id: "gpt-5-6-luna-pro", name: "OpenAI: GPT-5.6 Luna Pro" },
  { id: "gpt-5-6-sol", name: "GPT-5.6 Sol" },
  { id: "gpt-5-6-sol-pro", name: "OpenAI: GPT-5.6 Sol Pro" },
  { id: "gpt-5-6-terra", name: "GPT-5.6 Terra" },
  { id: "gpt-5-6-terra-pro", name: "OpenAI: GPT-5.6 Terra Pro" },
  { id: "gpt-5-chat", name: "GPT-5 Chat" },
  { id: "gpt-5-codex", name: "GPT-5-Codex" },
  { id: "gpt-5-image", name: "OpenAI: GPT-5 Image" },
  { id: "gpt-5-image-mini", name: "OpenAI: GPT-5 Image Mini" },
  { id: "gpt-5-mini", name: "GPT-5 Mini" },
  { id: "gpt-5-nano", name: "GPT-5 Nano" },
  { id: "gpt-5-pro", name: "GPT-5 pro" },
  { id: "gpt-audio", name: "OpenAI: GPT Audio" },
  { id: "gpt-audio-mini", name: "OpenAI: GPT Audio Mini" },
  { id: "gpt-chat-latest", name: "OpenAI: GPT Chat Latest" },
  { id: "gpt-image-1", name: "GPT-Image-1" },
  { id: "gpt-image-1-5", name: "GPT Image 1.5" },
  { id: "gpt-image-1-mini", name: "GPT-Image-1-Mini" },
  { id: "gpt-image-2", name: "GPT-Image-2" },
  { id: "gpt-latest", name: "OpenAI GPT Latest" },
  { id: "gpt-mini-latest", name: "OpenAI GPT Mini Latest" },
  { id: "gpt-oss-120b", name: "GPT-OSS-120B" },
  { id: "gpt-oss-120b-maas", name: "GPT OSS 120B" },
  { id: "gpt-oss-20b", name: "GPT OSS 20B" },
  { id: "gpt-oss-20b-maas", name: "GPT OSS 20B" },
  { id: "gpt-oss-safeguard-120b", name: "GPT OSS Safeguard 120B" },
  { id: "gpt-oss-safeguard-20b", name: "GPT OSS Safeguard 20B" },
  { id: "gpt-realtime-1-5", name: "GPT-Realtime-1.5" },
  { id: "gpt-realtime-2", name: "gpt-realtime-2" },
  { id: "gpt-realtime-2-1", name: "gpt-realtime-2.1" },
  { id: "gpt-realtime-mini", name: "GPT-Realtime mini" },
  { id: "gpt-realtime-whisper", name: "gpt-realtime-whisper" },
  { id: "granite-4-0-h-micro", name: "Granite 4.0 Micro" },
  { id: "granite-4-1-8b", name: "Granite 4.1 8B" },
  { id: "grok-4-20", name: "Grok 4.20 (Reasoning)" },
  { id: "grok-4-20-multi-agent", name: "Grok 4.20 Multi-Agent" },
  { id: "grok-4-3", name: "Grok 4.3" },
  { id: "grok-4-5", name: "Grok 4.5" },
  { id: "grok-build-0-1", name: "Grok Build 0.1" },
  { id: "grok-imagine-image-quality", name: "Grok Imagine Image Quality" },
  { id: "grok-latest", name: "xAI: Grok Latest" },
  { id: "hermes-3-llama-3-1-405b", name: "Nous: Hermes 3 405B Instruct" },
  { id: "hermes-3-llama-3-1-70b", name: "Hermes 3 70B Instruct" },
  { id: "hermes-4-405b", name: "Nous: Hermes 4 405B" },
  { id: "hermes-4-70b", name: "Nous: Hermes 4 70B" },
  { id: "hunyuan-a13b-instruct", name: "Hunyuan A13B Instruct" },
  { id: "hy3", name: "Hunyuan 3" },
  { id: "hy3-preview", name: "Hunyuan 3 Preview" },
  { id: "inkling", name: "Inkling" },
  { id: "inkling-small", name: "Inkling Small" },
  { id: "jamba-large-1-7", name: "AI21: Jamba Large 1.7" },
  { id: "kat-coder-air-v2-5", name: "Kat Coder Air V2.5" },
  { id: "kat-coder-pro-v2", name: "Kat Coder Pro V2" },
  { id: "kat-coder-pro-v2-5", name: "Kat Coder Pro V2.5" },
  { id: "kimi-k2", name: "Kimi K2 Thinking" },
  { id: "kimi-k2-5", name: "Kimi K2.5" },
  { id: "kimi-k2-6", name: "Kimi K2.6" },
  { id: "kimi-k2-7-code", name: "Kimi K2.7 Code" },
  { id: "kimi-k3", name: "Kimi K3" },
  { id: "kimi-latest", name: "MoonshotAI Kimi Latest" },
  { id: "krea-2-large", name: "Krea: Krea 2 Large" },
  { id: "krea-2-medium", name: "Krea: Krea 2 Medium" },
  { id: "krea-2-medium-turbo", name: "Krea: Krea 2 Medium Turbo" },
  { id: "l3-1-euryale-70b", name: "Llama 3.1 Euryale 70B v2.2" },
  { id: "l3-3-euryale-70b", name: "Llama 3.3 Euryale 70B" },
  { id: "l3-lunaris-8b", name: "Llama 3 8B Lunaris" },
  { id: "laguna-s-2-1", name: "Laguna S 2.1 Free" },
  { id: "laguna-xs-2-1", name: "Laguna XS 2.1" },
  { id: "ling-2-6-1t", name: "inclusionAI: Ling-2.6-1T" },
  { id: "ling-2-6-flash", name: "inclusionAI: Ling-2.6-flash" },
  { id: "ling-3-0-flash", name: "Ling 3.0 Flash" },
  { id: "ling-flash-2-0", name: "inclusionAI/Ling-flash-2.0" },
  { id: "llama-3-1-70b-instruct", name: "Llama 3.1 70b Instruct" },
  { id: "llama-3-1-8b-instruct", name: "Llama 3.1 8B Instruct" },
  { id: "llama-3-2-1b-instruct", name: "Llama 3.2 1b Instruct" },
  { id: "llama-3-2-3b-instruct", name: "Llama 3.2 3B Instruct" },
  { id: "llama-3-3-70b-instruct", name: "Llama 3.3 70b Instruct" },
  { id: "llama-4-maverick", name: "Llama-4-Maverick-17B-128E-Instruct-FP8" },
  { id: "llama-4-scout", name: "Llama-4-Scout-17B-16E-Instruct-FP8" },
  { id: "llama-guard-4-12b", name: "Llama Guard 4 12B" },
  { id: "longcat-2-0", name: "LongCat-2.0" },
  { id: "lyria-3-clip-preview", name: "Lyria 3 Clip Preview" },
  { id: "lyria-3-pro-preview", name: "Lyria 3 Pro Preview" },
  { id: "magnum-v4-72b", name: "Magnum v4 72B" },
  { id: "mai-image-2-5", name: "Microsoft: MAI-Image-2.5" },
  { id: "mai-image-2-5-pro", name: "Microsoft: MAI-Image-2.5 Pro" },
  { id: "mercury-2", name: "Mercury 2" },
  { id: "mimo-v2-5", name: "MiMo V2.5" },
  { id: "mimo-v2-5-pro", name: "MiMo V2.5 Pro" },
  { id: "mimo-v2-omni", name: "MiMo-V2-Omni" },
  { id: "mimo-v2-pro", name: "MiMo-V2-Pro" },
  { id: "minimax-01", name: "MiniMax: MiniMax-01" },
  { id: "minimax-m1", name: "MiniMax: MiniMax M1" },
  { id: "minimax-m2", name: "MiniMax M2" },
  { id: "minimax-m2-1", name: "MiniMax M2.1" },
  { id: "minimax-m2-5", name: "MiniMax M2.5" },
  { id: "minimax-m2-7", name: "MiniMax-M2.7" },
  { id: "minimax-m2-her", name: "MiniMax: MiniMax M2-her" },
  { id: "minimax-m3", name: "MiniMax-M3" },
  { id: "ministral-14b", name: "Ministral 14B" },
  { id: "ministral-3b", name: "Ministral 3B (latest)" },
  { id: "ministral-8b", name: "Ministral 8B (latest)" },
  { id: "mistral-large", name: "Mistral Large 2.1" },
  { id: "mistral-medium-3", name: "Mistral: Mistral Medium 3" },
  { id: "mistral-medium-3-1", name: "Mistral: Mistral Medium 3.1" },
  { id: "mistral-medium-3-5", name: "Mistral Medium Latest" },
  { id: "mistral-nemo", name: "Mistral Nemo" },
  { id: "mistral-saba", name: "Mistral: Saba" },
  { id: "mistral-small", name: "Mistral Small 3.2" },
  { id: "mistral-small-24b-instruct", name: "Mistral: Mistral Small 3" },
  { id: "mistral-small-3-1-24b-instruct", name: "Mistral: Mistral Small 3.1 24B" },
  { id: "mistral-small-3-2-24b-instruct", name: "Mistral: Mistral Small 3.2 24B" },
  { id: "mixtral-8x22b-instruct", name: "Mistral: Mixtral 8x22B Instruct" },
  { id: "morph-v3-fast", name: "Morph v3 Fast" },
  { id: "morph-v3-large", name: "Morph v3 Large" },
  { id: "muse-spark-1-1", name: "Muse Spark 1.1" },
  { id: "muse-spark-1-2", name: "Muse Spark 1.2" },
  { id: "mythomax-l2-13b", name: "MythoMax 13B" },
  { id: "nemotron-3-5-content-safety", name: "NVIDIA: Nemotron 3.5 Content Safety (free)" },
  { id: "nemotron-3-nano-30b-a3b", name: "nemotron-3-nano-30b-a3b" },
  { id: "nemotron-3-nano-omni-30b-a3b", name: "Nemotron 3 Nano Omni" },
  { id: "nemotron-3-super-120b-a12b", name: "Nemotron 3 Super" },
  { id: "nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra 550B A55B" },
  { id: "nemotron-nano-12b-v2-vl", name: "Nemotron Nano 12B v2 VL" },
  { id: "nemotron-nano-9b-v2", name: "nvidia-nemotron-nano-9b-v2" },
  { id: "nex-n2-mini", name: "Nex-N2-Mini" },
  { id: "nex-n2-pro", name: "Nex-N2-Pro" },
  { id: "north-mini-code", name: "North Mini Code" },
  { id: "nova-2-lite-v1", name: "Amazon: Nova 2 Lite" },
  { id: "nova-lite-v1", name: "Amazon: Nova Lite 1.0" },
  { id: "nova-micro-v1", name: "Amazon: Nova Micro 1.0" },
  { id: "nova-premier-v1", name: "Amazon: Nova Premier 1.0" },
  { id: "nova-pro-v1", name: "Amazon: Nova Pro 1.0" },
  { id: "o1", name: "o1" },
  { id: "o1-pro", name: "o1-pro" },
  { id: "o3", name: "o3" },
  { id: "o3-deep-research", name: "o3-deep-research" },
  { id: "o3-mini", name: "o3-mini" },
  { id: "o3-pro", name: "o3 Pro" },
  { id: "o4-mini", name: "o4-mini" },
  { id: "olmo-3-32b", name: "AllenAI: Olmo 3 32B Think" },
  { id: "palmyra-x5", name: "Palmyra X5" },
  { id: "perceptron-mk1", name: "Perceptron Mk1" },
  { id: "phi-4", name: "Microsoft: Phi 4" },
  { id: "qwen-2-5-72b-instruct", name: "Qwen2.5 72B Instruct" },
  { id: "qwen-2-5-7b-instruct", name: "Qwen: Qwen2.5 7B Instruct" },
  { id: "qwen-2-5-coder-32b-instruct", name: "Qwen2.5 Coder 32B Instruct" },
  { id: "qwen-image-3", name: "Qwen: Qwen Image 3" },
  { id: "qwen-image-3-pro", name: "Qwen: Qwen Image 3 Pro" },
  { id: "qwen-plus", name: "Qwen Plus" },
  { id: "qwen2-5-72b-instruct", name: "Qwen2.5 72B Instruct" },
  { id: "qwen2-5-7b-instruct", name: "Qwen2.5 7B Instruct" },
  { id: "qwen2-5-vl-72b-instruct", name: "Qwen2.5-VL 72B Instruct" },
  { id: "qwen3-14b", name: "Qwen3 14B" },
  { id: "qwen3-235b-a22b", name: "Qwen3 235B A22B 2507" },
  { id: "qwen3-30b-a3b", name: "Qwen: Qwen3 30B A3B Thinking 2507" },
  { id: "qwen3-30b-a3b-instruct", name: "Qwen: Qwen3 30B A3B Instruct 2507" },
  { id: "qwen3-32b", name: "Qwen3 32B (dense)" },
  { id: "qwen3-5-122b-a10b", name: "Qwen3.5 122B-A10B" },
  { id: "qwen3-5-27b", name: "Qwen3.5 27B" },
  { id: "qwen3-5-35b-a3b", name: "Qwen3.5 35B-A3B" },
  { id: "qwen3-5-397b-a17b", name: "Qwen3.5-397B-A17B" },
  { id: "qwen3-5-9b", name: "Qwen: Qwen3.5-9B" },
  { id: "qwen3-5-flash-02-23", name: "Qwen: Qwen3.5-Flash" },
  { id: "qwen3-5-plus", name: "Qwen3.5 Plus" },
  { id: "qwen3-5-plus-02-15", name: "Qwen: Qwen3.5 Plus 2026-02-15" },
  { id: "qwen3-6-27b", name: "Qwen3.6 27B" },
  { id: "qwen3-6-35b-a3b", name: "Qwen3.6 35B-A3B" },
  { id: "qwen3-6-flash", name: "Qwen3.6 Flash" },
  { id: "qwen3-6-max-preview", name: "Qwen3.6 Max Preview" },
  { id: "qwen3-6-plus", name: "Qwen3.6 Plus" },
  { id: "qwen3-7-flash", name: "Qwen 3.7 Flash" },
  { id: "qwen3-7-max", name: "Qwen3.7 Max" },
  { id: "qwen3-7-plus", name: "Qwen3.7 Plus" },
  { id: "qwen3-8-max", name: "Qwen3.8 Max" },
  { id: "qwen3-8b", name: "Qwen3 8B" },
  { id: "qwen3-coder", name: "Qwen3 Coder 480B A35B Instruct" },
  { id: "qwen3-coder-30b-a3b-instruct", name: "Qwen3-Coder 30B-A3B Instruct" },
  { id: "qwen3-coder-480b-a35b-instruct", name: "Qwen3 Coder 480B A35B Instruct" },
  { id: "qwen3-coder-flash", name: "Qwen3 Coder Flash" },
  { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
  { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
  { id: "qwen3-max", name: "Qwen3 Max" },
  { id: "qwen3-next-80b-a3b", name: "Qwen/Qwen3-Next-80B-A3B-Instruct" },
  { id: "qwen3-next-80b-a3b-instruct", name: "Qwen3-Next-80B-A3B-Instruct" },
  { id: "qwen3-vl-235b-a22b", name: "Qwen/Qwen3-VL-235B-A22B-Instruct" },
  { id: "qwen3-vl-235b-a22b-instruct", name: "Qwen3 VL 235B A22B Instruct" },
  { id: "qwen3-vl-30b-a3b", name: "Qwen3-VL 30B-A3B" },
  { id: "qwen3-vl-30b-a3b-instruct", name: "Qwen: Qwen3 VL 30B A3B Instruct" },
  { id: "qwen3-vl-32b", name: "Qwen/Qwen3-VL-32B-Thinking" },
  { id: "qwen3-vl-32b-instruct", name: "Qwen: Qwen3 VL 32B Instruct" },
  { id: "qwen3-vl-8b", name: "Qwen: Qwen3 VL 8B Thinking" },
  { id: "qwen3-vl-8b-instruct", name: "Qwen: Qwen3 VL 8B Instruct" },
  { id: "recraft-v3", name: "Recraft V3" },
  { id: "recraft-v4", name: "Recraft V4" },
  { id: "recraft-v4-1", name: "Recraft V4.1" },
  { id: "recraft-v4-1-pro", name: "Recraft V4.1 Pro" },
  { id: "recraft-v4-1-pro-vector", name: "Recraft: Recraft V4.1 Pro Vector" },
  { id: "recraft-v4-1-utility", name: "Recraft V4.1 Utility" },
  { id: "recraft-v4-1-utility-pro", name: "Recraft V4.1 Utility Pro" },
  { id: "recraft-v4-1-vector", name: "Recraft: Recraft V4.1 Vector" },
  { id: "recraft-v4-pro", name: "Recraft V4 Pro" },
  { id: "recraft-v4-pro-vector", name: "Recraft: Recraft V4 Pro Vector" },
  { id: "recraft-v4-vector", name: "Recraft: Recraft V4 Vector" },
  { id: "reka-edge", name: "Reka Edge" },
  { id: "reka-flash-3", name: "Reka Flash 3" },
  { id: "relace", name: "Relace Search" },
  { id: "relace-apply-3", name: "Relace Apply 3" },
  { id: "remm-slerp-l2-13b", name: "ReMM SLERP 13B" },
  { id: "ring-2-6-1t", name: "inclusionAI: Ring-2.6-1T" },
  { id: "riverflow-v2-5-fast", name: "Sourceful: Riverflow V2.5 Fast" },
  { id: "riverflow-v2-5-pro", name: "Sourceful: Riverflow V2.5 Pro" },
  { id: "riverflow-v2-fast", name: "Sourceful: Riverflow V2 Fast" },
  { id: "riverflow-v2-pro", name: "Sourceful: Riverflow V2 Pro" },
  { id: "rocinante-12b", name: "Rocinante 12B" },
  { id: "seed-1-6", name: "Seed 1.6" },
  { id: "seed-1-6-flash", name: "Seed 1.6 Flash" },
  { id: "seed-2-0-lite", name: "Seed-2.0-Lite" },
  { id: "seed-2-0-mini", name: "Seed-2.0-Mini" },
  { id: "seed-oss-36b-instruct", name: "ByteDance-Seed/Seed-OSS-36B-Instruct" },
  { id: "seedream-4-5", name: "Seedream 4.5" },
  { id: "skyfall-36b-v2", name: "Skyfall 36B V2" },
  { id: "solar-pro-3", name: "Upstage: Solar Pro 3" },
  { id: "sonar", name: "Sonar" },
  { id: "sonar-deep-research", name: "Perplexity Sonar Deep Research" },
  { id: "sonar-pro", name: "Sonar Pro" },
  { id: "sonar-reasoning-pro", name: "Sonar Reasoning Pro" },
  { id: "step-3-5-flash", name: "Step 3.5 Flash" },
  { id: "step-3-7-flash", name: "Step 3.7 Flash" },
  { id: "text-embedding-3-large", name: "text-embedding-3-large" },
  { id: "text-embedding-3-small", name: "text-embedding-3-small" },
  { id: "text-embedding-ada-002", name: "text-embedding-ada-002" },
  { id: "trinity-large", name: "Trinity Large Thinking" },
  { id: "ui-tars-1-5-7b", name: "UI-TARS 7B" },
  { id: "unslopnemo-12b", name: "UnslopNemo 12B" },
  { id: "virtuoso-large", name: "Virtuoso Large" },
  { id: "voxtral-small-24b", name: "Voxtral Small 24B 2507" },
  { id: "weaver", name: "Weaver (alpha)" },
  { id: "wizardlm-2-8x22b", name: "WizardLM-2 8x22B" },
];

/**
 * Provider-scoped wire ids that resolve to a catalog entry
 * (and optionally a provider-specific curated name).
 */
export const PROVIDER_MODEL_OVERRIDES: readonly ProviderModelOverride[] = [
  { providerId: "deepseek", modelId: "deepseek-chat" },
  { providerId: "deepseek", modelId: "deepseek-reasoner" },
  { providerId: "deepseek", modelId: "deepseek-v4-flash" },
  { providerId: "deepseek", modelId: "deepseek-v4-pro" },
  { providerId: "openrouter", modelId: "aion-2-0", apiModelId: "aion-labs/aion-2.0", name: "Aion-2.0" },
  { providerId: "openrouter", modelId: "aion-3-0", apiModelId: "aion-labs/aion-3.0", name: "Aion-3.0" },
  { providerId: "openrouter", modelId: "aion-3-0-mini", apiModelId: "aion-labs/aion-3.0-mini", name: "Aion-3.0-Mini" },
  { providerId: "openrouter", modelId: "aion-rp-llama-3-1-8b", apiModelId: "aion-labs/aion-rp-llama-3.1-8b", name: "Aion-RP 1.0 (8B)" },
  { providerId: "openrouter", modelId: "claude-3-haiku", apiModelId: "anthropic/claude-3-haiku" },
  { providerId: "openrouter", modelId: "claude-fable-5", apiModelId: "anthropic/claude-fable-5" },
  { providerId: "openrouter", modelId: "claude-fable-latest", apiModelId: "~anthropic/claude-fable-latest" },
  { providerId: "openrouter", modelId: "claude-haiku-4-5", apiModelId: "anthropic/claude-haiku-4.5" },
  { providerId: "openrouter", modelId: "claude-haiku-latest", apiModelId: "~anthropic/claude-haiku-latest" },
  { providerId: "openrouter", modelId: "claude-opus-4", apiModelId: "anthropic/claude-opus-4" },
  { providerId: "openrouter", modelId: "claude-opus-4-1", apiModelId: "anthropic/claude-opus-4.1" },
  { providerId: "openrouter", modelId: "claude-opus-4-5", apiModelId: "anthropic/claude-opus-4.5" },
  { providerId: "openrouter", modelId: "claude-opus-4-6", apiModelId: "anthropic/claude-opus-4.6" },
  { providerId: "openrouter", modelId: "claude-opus-4-7", apiModelId: "anthropic/claude-opus-4.7" },
  { providerId: "openrouter", modelId: "claude-opus-4-7-fast", apiModelId: "anthropic/claude-opus-4.7-fast" },
  { providerId: "openrouter", modelId: "claude-opus-4-8", apiModelId: "anthropic/claude-opus-4.8" },
  { providerId: "openrouter", modelId: "claude-opus-4-8-fast", apiModelId: "anthropic/claude-opus-4.8-fast" },
  { providerId: "openrouter", modelId: "claude-opus-5", apiModelId: "anthropic/claude-opus-5" },
  { providerId: "openrouter", modelId: "claude-opus-5-fast", apiModelId: "anthropic/claude-opus-5-fast" },
  { providerId: "openrouter", modelId: "claude-opus-latest", apiModelId: "~anthropic/claude-opus-latest" },
  { providerId: "openrouter", modelId: "claude-sonnet-4", apiModelId: "anthropic/claude-sonnet-4" },
  { providerId: "openrouter", modelId: "claude-sonnet-4-5", apiModelId: "anthropic/claude-sonnet-4.5" },
  { providerId: "openrouter", modelId: "claude-sonnet-4-6", apiModelId: "anthropic/claude-sonnet-4.6" },
  { providerId: "openrouter", modelId: "claude-sonnet-5", apiModelId: "anthropic/claude-sonnet-5" },
  { providerId: "openrouter", modelId: "claude-sonnet-latest", apiModelId: "~anthropic/claude-sonnet-latest" },
  { providerId: "openrouter", modelId: "codestral", apiModelId: "mistralai/codestral-2508" },
  { providerId: "openrouter", modelId: "cogito-v2-1-671b", apiModelId: "deepcogito/cogito-v2.1-671b" },
  { providerId: "openrouter", modelId: "command-a", apiModelId: "cohere/command-a" },
  { providerId: "openrouter", modelId: "command-r-08-2024", apiModelId: "cohere/command-r-08-2024" },
  { providerId: "openrouter", modelId: "command-r-plus-08-2024", apiModelId: "cohere/command-r-plus-08-2024" },
  { providerId: "openrouter", modelId: "command-r7b-12-2024", apiModelId: "cohere/command-r7b-12-2024" },
  { providerId: "openrouter", modelId: "cydonia-24b-v4-1", apiModelId: "thedrummer/cydonia-24b-v4.1", name: "Cydonia 24B V4.1" },
  { providerId: "openrouter", modelId: "deepseek-chat", apiModelId: "deepseek/deepseek-chat" },
  { providerId: "openrouter", modelId: "deepseek-chat-v3", apiModelId: "deepseek/deepseek-chat-v3-0324" },
  { providerId: "openrouter", modelId: "deepseek-chat-v3-1", apiModelId: "deepseek/deepseek-chat-v3.1" },
  { providerId: "openrouter", modelId: "deepseek-r1", apiModelId: "deepseek/deepseek-r1-0528" },
  { providerId: "openrouter", modelId: "deepseek-r1-distill-llama-70b", apiModelId: "deepseek/deepseek-r1-distill-llama-70b" },
  { providerId: "openrouter", modelId: "deepseek-v3-1-terminus", apiModelId: "deepseek/deepseek-v3.1-terminus" },
  { providerId: "openrouter", modelId: "deepseek-v3-2", apiModelId: "deepseek/deepseek-v3.2" },
  { providerId: "openrouter", modelId: "deepseek-v3-2-exp", apiModelId: "deepseek/deepseek-v3.2-exp" },
  { providerId: "openrouter", modelId: "deepseek-v4-flash", apiModelId: "deepseek/deepseek-v4-flash" },
  { providerId: "openrouter", modelId: "deepseek-v4-flash-latest", apiModelId: "~deepseek/deepseek-v4-flash-latest" },
  { providerId: "openrouter", modelId: "deepseek-v4-pro", apiModelId: "deepseek/deepseek-v4-pro" },
  { providerId: "openrouter", modelId: "dolphin-mistral-24b-venice-edition", apiModelId: "cognitivecomputations/dolphin-mistral-24b-venice-edition", name: "Uncensored" },
  { providerId: "openrouter", modelId: "ernie-4-5-vl-424b-a47b", apiModelId: "baidu/ernie-4.5-vl-424b-a47b" },
  { providerId: "openrouter", modelId: "flux-2-flex", apiModelId: "black-forest-labs/flux.2-flex" },
  { providerId: "openrouter", modelId: "flux-2-klein-4b", apiModelId: "black-forest-labs/flux.2-klein-4b" },
  { providerId: "openrouter", modelId: "flux-2-max", apiModelId: "black-forest-labs/flux.2-max" },
  { providerId: "openrouter", modelId: "flux-2-pro", apiModelId: "black-forest-labs/flux.2-pro" },
  { providerId: "openrouter", modelId: "free", apiModelId: "openrouter/free", name: "Free Models Router" },
  { providerId: "openrouter", modelId: "fugu-ultra", apiModelId: "sakana/fugu-ultra" },
  { providerId: "openrouter", modelId: "gemini-2-5-flash", apiModelId: "google/gemini-2.5-flash" },
  { providerId: "openrouter", modelId: "gemini-2-5-flash-image", apiModelId: "google/gemini-2.5-flash-image" },
  { providerId: "openrouter", modelId: "gemini-2-5-flash-lite", apiModelId: "google/gemini-2.5-flash-lite" },
  { providerId: "openrouter", modelId: "gemini-2-5-pro", apiModelId: "google/gemini-2.5-pro" },
  { providerId: "openrouter", modelId: "gemini-2-5-pro-preview", apiModelId: "google/gemini-2.5-pro-preview" },
  { providerId: "openrouter", modelId: "gemini-2-5-pro-preview-05-06", apiModelId: "google/gemini-2.5-pro-preview-05-06" },
  { providerId: "openrouter", modelId: "gemini-3-1-flash-image", apiModelId: "google/gemini-3.1-flash-image" },
  { providerId: "openrouter", modelId: "gemini-3-1-flash-image-preview", apiModelId: "google/gemini-3.1-flash-image-preview" },
  { providerId: "openrouter", modelId: "gemini-3-1-flash-lite", apiModelId: "google/gemini-3.1-flash-lite" },
  { providerId: "openrouter", modelId: "gemini-3-1-flash-lite-image", apiModelId: "google/gemini-3.1-flash-lite-image" },
  { providerId: "openrouter", modelId: "gemini-3-1-flash-lite-preview", apiModelId: "google/gemini-3.1-flash-lite-preview" },
  { providerId: "openrouter", modelId: "gemini-3-1-pro-preview", apiModelId: "google/gemini-3.1-pro-preview" },
  { providerId: "openrouter", modelId: "gemini-3-1-pro-preview-customtools", apiModelId: "google/gemini-3.1-pro-preview-customtools" },
  { providerId: "openrouter", modelId: "gemini-3-5-flash", apiModelId: "google/gemini-3.5-flash" },
  { providerId: "openrouter", modelId: "gemini-3-5-flash-lite", apiModelId: "google/gemini-3.5-flash-lite" },
  { providerId: "openrouter", modelId: "gemini-3-6-flash", apiModelId: "google/gemini-3.6-flash" },
  { providerId: "openrouter", modelId: "gemini-3-flash-preview", apiModelId: "google/gemini-3-flash-preview" },
  { providerId: "openrouter", modelId: "gemini-3-pro-image", apiModelId: "google/gemini-3-pro-image" },
  { providerId: "openrouter", modelId: "gemini-3-pro-image-preview", apiModelId: "google/gemini-3-pro-image-preview" },
  { providerId: "openrouter", modelId: "gemini-flash-latest", apiModelId: "~google/gemini-flash-latest" },
  { providerId: "openrouter", modelId: "gemini-pro-latest", apiModelId: "~google/gemini-pro-latest" },
  { providerId: "openrouter", modelId: "gemma-2-27b-it", apiModelId: "google/gemma-2-27b-it" },
  { providerId: "openrouter", modelId: "gemma-3-12b-it", apiModelId: "google/gemma-3-12b-it" },
  { providerId: "openrouter", modelId: "gemma-3-27b-it", apiModelId: "google/gemma-3-27b-it" },
  { providerId: "openrouter", modelId: "gemma-3-4b-it", apiModelId: "google/gemma-3-4b-it" },
  { providerId: "openrouter", modelId: "gemma-3n-e4b-it", apiModelId: "google/gemma-3n-e4b-it" },
  { providerId: "openrouter", modelId: "gemma-4-26b-a4b-it", apiModelId: "google/gemma-4-26b-a4b-it" },
  { providerId: "openrouter", modelId: "gemma-4-31b-it", apiModelId: "google/gemma-4-31b-it" },
  { providerId: "openrouter", modelId: "glm-4-5", apiModelId: "z-ai/glm-4.5" },
  { providerId: "openrouter", modelId: "glm-4-5-air", apiModelId: "z-ai/glm-4.5-air" },
  { providerId: "openrouter", modelId: "glm-4-5v", apiModelId: "z-ai/glm-4.5v" },
  { providerId: "openrouter", modelId: "glm-4-6", apiModelId: "z-ai/glm-4.6" },
  { providerId: "openrouter", modelId: "glm-4-6v", apiModelId: "z-ai/glm-4.6v" },
  { providerId: "openrouter", modelId: "glm-4-7", apiModelId: "z-ai/glm-4.7" },
  { providerId: "openrouter", modelId: "glm-4-7-flash", apiModelId: "z-ai/glm-4.7-flash" },
  { providerId: "openrouter", modelId: "glm-5", apiModelId: "z-ai/glm-5" },
  { providerId: "openrouter", modelId: "glm-5-1", apiModelId: "z-ai/glm-5.1" },
  { providerId: "openrouter", modelId: "glm-5-2", apiModelId: "z-ai/glm-5.2" },
  { providerId: "openrouter", modelId: "glm-5-turbo", apiModelId: "z-ai/glm-5-turbo" },
  { providerId: "openrouter", modelId: "glm-5v-turbo", apiModelId: "z-ai/glm-5v-turbo" },
  { providerId: "openrouter", modelId: "gpt-3-5-turbo", apiModelId: "openai/gpt-3.5-turbo-0613" },
  { providerId: "openrouter", modelId: "gpt-3-5-turbo-16k", apiModelId: "openai/gpt-3.5-turbo-16k" },
  { providerId: "openrouter", modelId: "gpt-3-5-turbo-instruct", apiModelId: "openai/gpt-3.5-turbo-instruct" },
  { providerId: "openrouter", modelId: "gpt-4", apiModelId: "openai/gpt-4" },
  { providerId: "openrouter", modelId: "gpt-4-1", apiModelId: "openai/gpt-4.1" },
  { providerId: "openrouter", modelId: "gpt-4-1-mini", apiModelId: "openai/gpt-4.1-mini" },
  { providerId: "openrouter", modelId: "gpt-4-1-nano", apiModelId: "openai/gpt-4.1-nano" },
  { providerId: "openrouter", modelId: "gpt-4-turbo", apiModelId: "openai/gpt-4-turbo" },
  { providerId: "openrouter", modelId: "gpt-4-turbo-preview", apiModelId: "openai/gpt-4-turbo-preview" },
  { providerId: "openrouter", modelId: "gpt-4o", apiModelId: "openai/gpt-4o" },
  { providerId: "openrouter", modelId: "gpt-4o-mini", apiModelId: "openai/gpt-4o-mini-2024-07-18" },
  { providerId: "openrouter", modelId: "gpt-5", apiModelId: "openai/gpt-5" },
  { providerId: "openrouter", modelId: "gpt-5-1", apiModelId: "openai/gpt-5.1" },
  { providerId: "openrouter", modelId: "gpt-5-1-codex", apiModelId: "openai/gpt-5.1-codex" },
  { providerId: "openrouter", modelId: "gpt-5-1-codex-max", apiModelId: "openai/gpt-5.1-codex-max" },
  { providerId: "openrouter", modelId: "gpt-5-1-codex-mini", apiModelId: "openai/gpt-5.1-codex-mini" },
  { providerId: "openrouter", modelId: "gpt-5-2", apiModelId: "openai/gpt-5.2" },
  { providerId: "openrouter", modelId: "gpt-5-2-chat", apiModelId: "openai/gpt-5.2-chat" },
  { providerId: "openrouter", modelId: "gpt-5-2-codex", apiModelId: "openai/gpt-5.2-codex" },
  { providerId: "openrouter", modelId: "gpt-5-2-pro", apiModelId: "openai/gpt-5.2-pro" },
  { providerId: "openrouter", modelId: "gpt-5-3-chat", apiModelId: "openai/gpt-5.3-chat" },
  { providerId: "openrouter", modelId: "gpt-5-3-codex", apiModelId: "openai/gpt-5.3-codex" },
  { providerId: "openrouter", modelId: "gpt-5-4", apiModelId: "openai/gpt-5.4" },
  { providerId: "openrouter", modelId: "gpt-5-4-image-2", apiModelId: "openai/gpt-5.4-image-2" },
  { providerId: "openrouter", modelId: "gpt-5-4-mini", apiModelId: "openai/gpt-5.4-mini" },
  { providerId: "openrouter", modelId: "gpt-5-4-nano", apiModelId: "openai/gpt-5.4-nano" },
  { providerId: "openrouter", modelId: "gpt-5-4-pro", apiModelId: "openai/gpt-5.4-pro" },
  { providerId: "openrouter", modelId: "gpt-5-5", apiModelId: "openai/gpt-5.5" },
  { providerId: "openrouter", modelId: "gpt-5-5-pro", apiModelId: "openai/gpt-5.5-pro" },
  { providerId: "openrouter", modelId: "gpt-5-6-luna", apiModelId: "openai/gpt-5.6-luna" },
  { providerId: "openrouter", modelId: "gpt-5-6-luna-pro", apiModelId: "openai/gpt-5.6-luna-pro" },
  { providerId: "openrouter", modelId: "gpt-5-6-sol", apiModelId: "openai/gpt-5.6-sol" },
  { providerId: "openrouter", modelId: "gpt-5-6-sol-pro", apiModelId: "openai/gpt-5.6-sol-pro" },
  { providerId: "openrouter", modelId: "gpt-5-6-terra", apiModelId: "openai/gpt-5.6-terra" },
  { providerId: "openrouter", modelId: "gpt-5-6-terra-pro", apiModelId: "openai/gpt-5.6-terra-pro" },
  { providerId: "openrouter", modelId: "gpt-5-image", apiModelId: "openai/gpt-5-image" },
  { providerId: "openrouter", modelId: "gpt-5-image-mini", apiModelId: "openai/gpt-5-image-mini" },
  { providerId: "openrouter", modelId: "gpt-5-mini", apiModelId: "openai/gpt-5-mini" },
  { providerId: "openrouter", modelId: "gpt-5-nano", apiModelId: "openai/gpt-5-nano" },
  { providerId: "openrouter", modelId: "gpt-5-pro", apiModelId: "openai/gpt-5-pro" },
  { providerId: "openrouter", modelId: "gpt-audio", apiModelId: "openai/gpt-audio" },
  { providerId: "openrouter", modelId: "gpt-audio-mini", apiModelId: "openai/gpt-audio-mini" },
  { providerId: "openrouter", modelId: "gpt-chat-latest", apiModelId: "openai/gpt-chat-latest" },
  { providerId: "openrouter", modelId: "gpt-image-1", apiModelId: "openai/gpt-image-1" },
  { providerId: "openrouter", modelId: "gpt-image-1-mini", apiModelId: "openai/gpt-image-1-mini" },
  { providerId: "openrouter", modelId: "gpt-image-2", apiModelId: "openai/gpt-image-2" },
  { providerId: "openrouter", modelId: "gpt-latest", apiModelId: "~openai/gpt-latest" },
  { providerId: "openrouter", modelId: "gpt-mini-latest", apiModelId: "~openai/gpt-mini-latest" },
  { providerId: "openrouter", modelId: "gpt-oss-120b", apiModelId: "openai/gpt-oss-120b" },
  { providerId: "openrouter", modelId: "gpt-oss-20b", apiModelId: "openai/gpt-oss-20b" },
  { providerId: "openrouter", modelId: "gpt-oss-safeguard-20b", apiModelId: "openai/gpt-oss-safeguard-20b" },
  { providerId: "openrouter", modelId: "granite-4-0-h-micro", apiModelId: "ibm-granite/granite-4.0-h-micro", name: "Granite 4.0 Micro" },
  { providerId: "openrouter", modelId: "granite-4-1-8b", apiModelId: "ibm-granite/granite-4.1-8b", name: "Granite 4.1 8B" },
  { providerId: "openrouter", modelId: "grok-4-20", apiModelId: "x-ai/grok-4.20" },
  { providerId: "openrouter", modelId: "grok-4-20-multi-agent", apiModelId: "x-ai/grok-4.20-multi-agent" },
  { providerId: "openrouter", modelId: "grok-4-3", apiModelId: "x-ai/grok-4.3" },
  { providerId: "openrouter", modelId: "grok-4-5", apiModelId: "x-ai/grok-4.5" },
  { providerId: "openrouter", modelId: "grok-build-0-1", apiModelId: "x-ai/grok-build-0.1" },
  { providerId: "openrouter", modelId: "grok-imagine-image-quality", apiModelId: "x-ai/grok-imagine-image-quality" },
  { providerId: "openrouter", modelId: "grok-latest", apiModelId: "~x-ai/grok-latest" },
  { providerId: "openrouter", modelId: "hermes-3-llama-3-1-405b", apiModelId: "nousresearch/hermes-3-llama-3.1-405b" },
  { providerId: "openrouter", modelId: "hermes-3-llama-3-1-70b", apiModelId: "nousresearch/hermes-3-llama-3.1-70b", name: "Hermes 3 70B Instruct" },
  { providerId: "openrouter", modelId: "hermes-4-405b", apiModelId: "nousresearch/hermes-4-405b" },
  { providerId: "openrouter", modelId: "hermes-4-70b", apiModelId: "nousresearch/hermes-4-70b" },
  { providerId: "openrouter", modelId: "hunyuan-a13b-instruct", apiModelId: "tencent/hunyuan-a13b-instruct" },
  { providerId: "openrouter", modelId: "hy3", apiModelId: "tencent/hy3" },
  { providerId: "openrouter", modelId: "hy3-preview", apiModelId: "tencent/hy3-preview" },
  { providerId: "openrouter", modelId: "inkling", apiModelId: "thinkingmachines/inkling" },
  { providerId: "openrouter", modelId: "inkling-small", apiModelId: "thinkingmachines/inkling-small" },
  { providerId: "openrouter", modelId: "jamba-large-1-7", apiModelId: "ai21/jamba-large-1.7" },
  { providerId: "openrouter", modelId: "kat-coder-air-v2-5", apiModelId: "kwaipilot/kat-coder-air-v2.5" },
  { providerId: "openrouter", modelId: "kat-coder-pro-v2", apiModelId: "kwaipilot/kat-coder-pro-v2" },
  { providerId: "openrouter", modelId: "kat-coder-pro-v2-5", apiModelId: "kwaipilot/kat-coder-pro-v2.5" },
  { providerId: "openrouter", modelId: "kimi-k2", apiModelId: "moonshotai/kimi-k2" },
  { providerId: "openrouter", modelId: "kimi-k2-5", apiModelId: "moonshotai/kimi-k2.5" },
  { providerId: "openrouter", modelId: "kimi-k2-6", apiModelId: "moonshotai/kimi-k2.6" },
  { providerId: "openrouter", modelId: "kimi-k2-7-code", apiModelId: "moonshotai/kimi-k2.7-code" },
  { providerId: "openrouter", modelId: "kimi-k3", apiModelId: "moonshotai/kimi-k3" },
  { providerId: "openrouter", modelId: "kimi-latest", apiModelId: "~moonshotai/kimi-latest" },
  { providerId: "openrouter", modelId: "krea-2-large", apiModelId: "krea/krea-2-large", name: "Krea: Krea 2 Large" },
  { providerId: "openrouter", modelId: "krea-2-medium", apiModelId: "krea/krea-2-medium", name: "Krea: Krea 2 Medium" },
  { providerId: "openrouter", modelId: "krea-2-medium-turbo", apiModelId: "krea/krea-2-medium-turbo", name: "Krea: Krea 2 Medium Turbo" },
  { providerId: "openrouter", modelId: "l3-1-euryale-70b", apiModelId: "sao10k/l3.1-euryale-70b", name: "Llama 3.1 Euryale 70B v2.2" },
  { providerId: "openrouter", modelId: "l3-3-euryale-70b", apiModelId: "sao10k/l3.3-euryale-70b", name: "Llama 3.3 Euryale 70B" },
  { providerId: "openrouter", modelId: "l3-lunaris-8b", apiModelId: "sao10k/l3-lunaris-8b", name: "Llama 3 8B Lunaris" },
  { providerId: "openrouter", modelId: "laguna-s-2-1", apiModelId: "poolside/laguna-s-2.1" },
  { providerId: "openrouter", modelId: "laguna-xs-2-1", apiModelId: "poolside/laguna-xs-2.1" },
  { providerId: "openrouter", modelId: "ling-2-6-1t", apiModelId: "inclusionai/ling-2.6-1t" },
  { providerId: "openrouter", modelId: "ling-2-6-flash", apiModelId: "inclusionai/ling-2.6-flash" },
  { providerId: "openrouter", modelId: "ling-3-0-flash", apiModelId: "inclusionai/ling-3.0-flash:free" },
  { providerId: "openrouter", modelId: "llama-3-1-70b-instruct", apiModelId: "meta-llama/llama-3.1-70b-instruct" },
  { providerId: "openrouter", modelId: "llama-3-1-8b-instruct", apiModelId: "meta-llama/llama-3.1-8b-instruct" },
  { providerId: "openrouter", modelId: "llama-3-2-1b-instruct", apiModelId: "meta-llama/llama-3.2-1b-instruct" },
  { providerId: "openrouter", modelId: "llama-3-2-3b-instruct", apiModelId: "meta-llama/llama-3.2-3b-instruct" },
  { providerId: "openrouter", modelId: "llama-3-3-70b-instruct", apiModelId: "meta-llama/llama-3.3-70b-instruct" },
  { providerId: "openrouter", modelId: "llama-4-maverick", apiModelId: "meta-llama/llama-4-maverick" },
  { providerId: "openrouter", modelId: "llama-4-scout", apiModelId: "meta-llama/llama-4-scout" },
  { providerId: "openrouter", modelId: "llama-guard-4-12b", apiModelId: "meta-llama/llama-guard-4-12b" },
  { providerId: "openrouter", modelId: "longcat-2-0", apiModelId: "meituan/longcat-2.0" },
  { providerId: "openrouter", modelId: "lyria-3-clip-preview", apiModelId: "google/lyria-3-clip-preview" },
  { providerId: "openrouter", modelId: "lyria-3-pro-preview", apiModelId: "google/lyria-3-pro-preview" },
  { providerId: "openrouter", modelId: "magnum-v4-72b", apiModelId: "anthracite-org/magnum-v4-72b", name: "Magnum v4 72B" },
  { providerId: "openrouter", modelId: "mai-image-2-5", apiModelId: "microsoft/mai-image-2.5" },
  { providerId: "openrouter", modelId: "mai-image-2-5-pro", apiModelId: "microsoft/mai-image-2.5-pro" },
  { providerId: "openrouter", modelId: "mercury-2", apiModelId: "inception/mercury-2" },
  { providerId: "openrouter", modelId: "mimo-v2-5", apiModelId: "xiaomi/mimo-v2.5" },
  { providerId: "openrouter", modelId: "mimo-v2-5-pro", apiModelId: "xiaomi/mimo-v2.5-pro" },
  { providerId: "openrouter", modelId: "minimax-01", apiModelId: "minimax/minimax-01" },
  { providerId: "openrouter", modelId: "minimax-m1", apiModelId: "minimax/minimax-m1" },
  { providerId: "openrouter", modelId: "minimax-m2", apiModelId: "minimax/minimax-m2" },
  { providerId: "openrouter", modelId: "minimax-m2-1", apiModelId: "minimax/minimax-m2.1" },
  { providerId: "openrouter", modelId: "minimax-m2-5", apiModelId: "minimax/minimax-m2.5" },
  { providerId: "openrouter", modelId: "minimax-m2-7", apiModelId: "minimax/minimax-m2.7" },
  { providerId: "openrouter", modelId: "minimax-m2-her", apiModelId: "minimax/minimax-m2-her" },
  { providerId: "openrouter", modelId: "minimax-m3", apiModelId: "minimax/minimax-m3" },
  { providerId: "openrouter", modelId: "ministral-14b", apiModelId: "mistralai/ministral-14b-2512" },
  { providerId: "openrouter", modelId: "ministral-3b", apiModelId: "mistralai/ministral-3b-2512" },
  { providerId: "openrouter", modelId: "ministral-8b", apiModelId: "mistralai/ministral-8b-2512" },
  { providerId: "openrouter", modelId: "mistral-large", apiModelId: "mistralai/mistral-large" },
  { providerId: "openrouter", modelId: "mistral-medium-3", apiModelId: "mistralai/mistral-medium-3" },
  { providerId: "openrouter", modelId: "mistral-medium-3-1", apiModelId: "mistralai/mistral-medium-3.1" },
  { providerId: "openrouter", modelId: "mistral-medium-3-5", apiModelId: "mistralai/mistral-medium-3-5" },
  { providerId: "openrouter", modelId: "mistral-nemo", apiModelId: "mistralai/mistral-nemo" },
  { providerId: "openrouter", modelId: "mistral-saba", apiModelId: "mistralai/mistral-saba" },
  { providerId: "openrouter", modelId: "mistral-small", apiModelId: "mistralai/mistral-small-2603" },
  { providerId: "openrouter", modelId: "mistral-small-24b-instruct", apiModelId: "mistralai/mistral-small-24b-instruct-2501" },
  { providerId: "openrouter", modelId: "mistral-small-3-1-24b-instruct", apiModelId: "mistralai/mistral-small-3.1-24b-instruct" },
  { providerId: "openrouter", modelId: "mistral-small-3-2-24b-instruct", apiModelId: "mistralai/mistral-small-3.2-24b-instruct" },
  { providerId: "openrouter", modelId: "mixtral-8x22b-instruct", apiModelId: "mistralai/mixtral-8x22b-instruct" },
  { providerId: "openrouter", modelId: "morph-v3-fast", apiModelId: "morph/morph-v3-fast" },
  { providerId: "openrouter", modelId: "morph-v3-large", apiModelId: "morph/morph-v3-large" },
  { providerId: "openrouter", modelId: "muse-spark-1-1", apiModelId: "meta/muse-spark-1.1" },
  { providerId: "openrouter", modelId: "muse-spark-1-2", apiModelId: "meta/muse-spark-1.2", name: "Muse Spark 1.2" },
  { providerId: "openrouter", modelId: "mythomax-l2-13b", apiModelId: "gryphe/mythomax-l2-13b", name: "MythoMax 13B" },
  { providerId: "openrouter", modelId: "nemotron-3-5-content-safety", apiModelId: "nvidia/nemotron-3.5-content-safety:free" },
  { providerId: "openrouter", modelId: "nemotron-3-nano-30b-a3b", apiModelId: "nvidia/nemotron-3-nano-30b-a3b" },
  { providerId: "openrouter", modelId: "nemotron-3-nano-omni-30b-a3b", apiModelId: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free" },
  { providerId: "openrouter", modelId: "nemotron-3-super-120b-a12b", apiModelId: "nvidia/nemotron-3-super-120b-a12b" },
  { providerId: "openrouter", modelId: "nemotron-3-ultra-550b-a55b", apiModelId: "nvidia/nemotron-3-ultra-550b-a55b:free" },
  { providerId: "openrouter", modelId: "nemotron-nano-12b-v2-vl", apiModelId: "nvidia/nemotron-nano-12b-v2-vl:free" },
  { providerId: "openrouter", modelId: "nemotron-nano-9b-v2", apiModelId: "nvidia/nemotron-nano-9b-v2:free" },
  { providerId: "openrouter", modelId: "nex-n2-mini", apiModelId: "nex-agi/nex-n2-mini", name: "Nex-N2-Mini" },
  { providerId: "openrouter", modelId: "nex-n2-pro", apiModelId: "nex-agi/nex-n2-pro", name: "Nex-N2-Pro" },
  { providerId: "openrouter", modelId: "north-mini-code", apiModelId: "cohere/north-mini-code:free" },
  { providerId: "openrouter", modelId: "nova-2-lite-v1", apiModelId: "amazon/nova-2-lite-v1" },
  { providerId: "openrouter", modelId: "nova-lite-v1", apiModelId: "amazon/nova-lite-v1" },
  { providerId: "openrouter", modelId: "nova-micro-v1", apiModelId: "amazon/nova-micro-v1" },
  { providerId: "openrouter", modelId: "nova-premier-v1", apiModelId: "amazon/nova-premier-v1" },
  { providerId: "openrouter", modelId: "nova-pro-v1", apiModelId: "amazon/nova-pro-v1" },
  { providerId: "openrouter", modelId: "o1", apiModelId: "openai/o1" },
  { providerId: "openrouter", modelId: "o1-pro", apiModelId: "openai/o1-pro" },
  { providerId: "openrouter", modelId: "o3", apiModelId: "openai/o3" },
  { providerId: "openrouter", modelId: "o3-mini", apiModelId: "openai/o3-mini-high" },
  { providerId: "openrouter", modelId: "o3-pro", apiModelId: "openai/o3-pro" },
  { providerId: "openrouter", modelId: "o4-mini", apiModelId: "openai/o4-mini-high" },
  { providerId: "openrouter", modelId: "olmo-3-32b", apiModelId: "allenai/olmo-3-32b-think" },
  { providerId: "openrouter", modelId: "palmyra-x5", apiModelId: "writer/palmyra-x5" },
  { providerId: "openrouter", modelId: "perceptron-mk1", apiModelId: "perceptron/perceptron-mk1", name: "Perceptron Mk1" },
  { providerId: "openrouter", modelId: "phi-4", apiModelId: "microsoft/phi-4" },
  { providerId: "openrouter", modelId: "qwen-2-5-72b-instruct", apiModelId: "qwen/qwen-2.5-72b-instruct" },
  { providerId: "openrouter", modelId: "qwen-2-5-7b-instruct", apiModelId: "qwen/qwen-2.5-7b-instruct" },
  { providerId: "openrouter", modelId: "qwen-2-5-coder-32b-instruct", apiModelId: "qwen/qwen-2.5-coder-32b-instruct" },
  { providerId: "openrouter", modelId: "qwen-image-3", apiModelId: "qwen/qwen-image-3" },
  { providerId: "openrouter", modelId: "qwen-image-3-pro", apiModelId: "qwen/qwen-image-3-pro" },
  { providerId: "openrouter", modelId: "qwen-plus", apiModelId: "qwen/qwen-plus-2025-07-28:thinking" },
  { providerId: "openrouter", modelId: "qwen2-5-vl-72b-instruct", apiModelId: "qwen/qwen2.5-vl-72b-instruct" },
  { providerId: "openrouter", modelId: "qwen3-14b", apiModelId: "qwen/qwen3-14b" },
  { providerId: "openrouter", modelId: "qwen3-235b-a22b", apiModelId: "qwen/qwen3-235b-a22b-thinking-2507" },
  { providerId: "openrouter", modelId: "qwen3-30b-a3b", apiModelId: "qwen/qwen3-30b-a3b" },
  { providerId: "openrouter", modelId: "qwen3-30b-a3b-instruct", apiModelId: "qwen/qwen3-30b-a3b-instruct-2507" },
  { providerId: "openrouter", modelId: "qwen3-32b", apiModelId: "qwen/qwen3-32b" },
  { providerId: "openrouter", modelId: "qwen3-5-122b-a10b", apiModelId: "qwen/qwen3.5-122b-a10b" },
  { providerId: "openrouter", modelId: "qwen3-5-27b", apiModelId: "qwen/qwen3.5-27b" },
  { providerId: "openrouter", modelId: "qwen3-5-35b-a3b", apiModelId: "qwen/qwen3.5-35b-a3b" },
  { providerId: "openrouter", modelId: "qwen3-5-397b-a17b", apiModelId: "qwen/qwen3.5-397b-a17b" },
  { providerId: "openrouter", modelId: "qwen3-5-9b", apiModelId: "qwen/qwen3.5-9b" },
  { providerId: "openrouter", modelId: "qwen3-5-flash-02-23", apiModelId: "qwen/qwen3.5-flash-02-23" },
  { providerId: "openrouter", modelId: "qwen3-5-plus", apiModelId: "qwen/qwen3.5-plus-20260420" },
  { providerId: "openrouter", modelId: "qwen3-5-plus-02-15", apiModelId: "qwen/qwen3.5-plus-02-15" },
  { providerId: "openrouter", modelId: "qwen3-6-27b", apiModelId: "qwen/qwen3.6-27b" },
  { providerId: "openrouter", modelId: "qwen3-6-35b-a3b", apiModelId: "qwen/qwen3.6-35b-a3b" },
  { providerId: "openrouter", modelId: "qwen3-6-flash", apiModelId: "qwen/qwen3.6-flash" },
  { providerId: "openrouter", modelId: "qwen3-6-max-preview", apiModelId: "qwen/qwen3.6-max-preview" },
  { providerId: "openrouter", modelId: "qwen3-6-plus", apiModelId: "qwen/qwen3.6-plus" },
  { providerId: "openrouter", modelId: "qwen3-7-flash", apiModelId: "qwen/qwen3.7-flash" },
  { providerId: "openrouter", modelId: "qwen3-7-max", apiModelId: "qwen/qwen3.7-max" },
  { providerId: "openrouter", modelId: "qwen3-7-plus", apiModelId: "qwen/qwen3.7-plus" },
  { providerId: "openrouter", modelId: "qwen3-8-max", apiModelId: "qwen/qwen3.8-max" },
  { providerId: "openrouter", modelId: "qwen3-8b", apiModelId: "qwen/qwen3-8b" },
  { providerId: "openrouter", modelId: "qwen3-coder", apiModelId: "qwen/qwen3-coder" },
  { providerId: "openrouter", modelId: "qwen3-coder-30b-a3b-instruct", apiModelId: "qwen/qwen3-coder-30b-a3b-instruct" },
  { providerId: "openrouter", modelId: "qwen3-coder-flash", apiModelId: "qwen/qwen3-coder-flash" },
  { providerId: "openrouter", modelId: "qwen3-coder-next", apiModelId: "qwen/qwen3-coder-next" },
  { providerId: "openrouter", modelId: "qwen3-coder-plus", apiModelId: "qwen/qwen3-coder-plus" },
  { providerId: "openrouter", modelId: "qwen3-max", apiModelId: "qwen/qwen3-max" },
  { providerId: "openrouter", modelId: "qwen3-next-80b-a3b", apiModelId: "qwen/qwen3-next-80b-a3b-thinking" },
  { providerId: "openrouter", modelId: "qwen3-next-80b-a3b-instruct", apiModelId: "qwen/qwen3-next-80b-a3b-instruct" },
  { providerId: "openrouter", modelId: "qwen3-vl-235b-a22b", apiModelId: "qwen/qwen3-vl-235b-a22b-thinking" },
  { providerId: "openrouter", modelId: "qwen3-vl-235b-a22b-instruct", apiModelId: "qwen/qwen3-vl-235b-a22b-instruct" },
  { providerId: "openrouter", modelId: "qwen3-vl-30b-a3b", apiModelId: "qwen/qwen3-vl-30b-a3b-thinking" },
  { providerId: "openrouter", modelId: "qwen3-vl-30b-a3b-instruct", apiModelId: "qwen/qwen3-vl-30b-a3b-instruct" },
  { providerId: "openrouter", modelId: "qwen3-vl-32b-instruct", apiModelId: "qwen/qwen3-vl-32b-instruct" },
  { providerId: "openrouter", modelId: "qwen3-vl-8b", apiModelId: "qwen/qwen3-vl-8b-thinking" },
  { providerId: "openrouter", modelId: "qwen3-vl-8b-instruct", apiModelId: "qwen/qwen3-vl-8b-instruct" },
  { providerId: "openrouter", modelId: "recraft-v3", apiModelId: "recraft/recraft-v3" },
  { providerId: "openrouter", modelId: "recraft-v4", apiModelId: "recraft/recraft-v4" },
  { providerId: "openrouter", modelId: "recraft-v4-1", apiModelId: "recraft/recraft-v4.1" },
  { providerId: "openrouter", modelId: "recraft-v4-1-pro", apiModelId: "recraft/recraft-v4.1-pro" },
  { providerId: "openrouter", modelId: "recraft-v4-1-pro-vector", apiModelId: "recraft/recraft-v4.1-pro-vector" },
  { providerId: "openrouter", modelId: "recraft-v4-1-utility", apiModelId: "recraft/recraft-v4.1-utility" },
  { providerId: "openrouter", modelId: "recraft-v4-1-utility-pro", apiModelId: "recraft/recraft-v4.1-utility-pro" },
  { providerId: "openrouter", modelId: "recraft-v4-1-vector", apiModelId: "recraft/recraft-v4.1-vector" },
  { providerId: "openrouter", modelId: "recraft-v4-pro", apiModelId: "recraft/recraft-v4-pro" },
  { providerId: "openrouter", modelId: "recraft-v4-pro-vector", apiModelId: "recraft/recraft-v4-pro-vector" },
  { providerId: "openrouter", modelId: "recraft-v4-vector", apiModelId: "recraft/recraft-v4-vector" },
  { providerId: "openrouter", modelId: "reka-edge", apiModelId: "rekaai/reka-edge" },
  { providerId: "openrouter", modelId: "reka-flash-3", apiModelId: "rekaai/reka-flash-3" },
  { providerId: "openrouter", modelId: "relace", apiModelId: "relace/relace-search", name: "Relace Search" },
  { providerId: "openrouter", modelId: "relace-apply-3", apiModelId: "relace/relace-apply-3", name: "Relace Apply 3" },
  { providerId: "openrouter", modelId: "remm-slerp-l2-13b", apiModelId: "undi95/remm-slerp-l2-13b", name: "ReMM SLERP 13B" },
  { providerId: "openrouter", modelId: "ring-2-6-1t", apiModelId: "inclusionai/ring-2.6-1t" },
  { providerId: "openrouter", modelId: "riverflow-v2-5-fast", apiModelId: "sourceful/riverflow-v2.5-fast" },
  { providerId: "openrouter", modelId: "riverflow-v2-5-pro", apiModelId: "sourceful/riverflow-v2.5-pro" },
  { providerId: "openrouter", modelId: "riverflow-v2-fast", apiModelId: "sourceful/riverflow-v2-fast" },
  { providerId: "openrouter", modelId: "riverflow-v2-pro", apiModelId: "sourceful/riverflow-v2-pro" },
  { providerId: "openrouter", modelId: "rocinante-12b", apiModelId: "thedrummer/rocinante-12b", name: "Rocinante 12B" },
  { providerId: "openrouter", modelId: "seed-1-6", apiModelId: "bytedance-seed/seed-1.6" },
  { providerId: "openrouter", modelId: "seed-1-6-flash", apiModelId: "bytedance-seed/seed-1.6-flash", name: "Seed 1.6 Flash" },
  { providerId: "openrouter", modelId: "seed-2-0-lite", apiModelId: "bytedance-seed/seed-2.0-lite", name: "Seed-2.0-Lite" },
  { providerId: "openrouter", modelId: "seed-2-0-mini", apiModelId: "bytedance-seed/seed-2.0-mini", name: "Seed-2.0-Mini" },
  { providerId: "openrouter", modelId: "seedream-4-5", apiModelId: "bytedance-seed/seedream-4.5" },
  { providerId: "openrouter", modelId: "skyfall-36b-v2", apiModelId: "thedrummer/skyfall-36b-v2", name: "Skyfall 36B V2" },
  { providerId: "openrouter", modelId: "solar-pro-3", apiModelId: "upstage/solar-pro-3" },
  { providerId: "openrouter", modelId: "sonar", apiModelId: "perplexity/sonar" },
  { providerId: "openrouter", modelId: "sonar-deep-research", apiModelId: "perplexity/sonar-deep-research" },
  { providerId: "openrouter", modelId: "sonar-pro", apiModelId: "perplexity/sonar-pro-search" },
  { providerId: "openrouter", modelId: "sonar-reasoning-pro", apiModelId: "perplexity/sonar-reasoning-pro" },
  { providerId: "openrouter", modelId: "step-3-5-flash", apiModelId: "stepfun/step-3.5-flash" },
  { providerId: "openrouter", modelId: "step-3-7-flash", apiModelId: "stepfun/step-3.7-flash" },
  { providerId: "openrouter", modelId: "trinity-large", apiModelId: "arcee-ai/trinity-large-thinking" },
  { providerId: "openrouter", modelId: "ui-tars-1-5-7b", apiModelId: "bytedance/ui-tars-1.5-7b", name: "UI-TARS 7B" },
  { providerId: "openrouter", modelId: "unslopnemo-12b", apiModelId: "thedrummer/unslopnemo-12b", name: "UnslopNemo 12B" },
  { providerId: "openrouter", modelId: "virtuoso-large", apiModelId: "arcee-ai/virtuoso-large", name: "Virtuoso Large" },
  { providerId: "openrouter", modelId: "voxtral-small-24b", apiModelId: "mistralai/voxtral-small-24b-2507" },
  { providerId: "openrouter", modelId: "weaver", apiModelId: "mancer/weaver", name: "Weaver (alpha)" },
  { providerId: "openrouter", modelId: "wizardlm-2-8x22b", apiModelId: "microsoft/wizardlm-2-8x22b", name: "WizardLM-2 8x22B" },
  { providerId: "siliconflow", modelId: "deepseek-r1", apiModelId: "deepseek-ai/DeepSeek-R1" },
  { providerId: "siliconflow", modelId: "deepseek-v3", apiModelId: "deepseek-ai/DeepSeek-V3" },
  { providerId: "siliconflow", modelId: "deepseek-v3-1", apiModelId: "deepseek-ai/DeepSeek-V3.1" },
  { providerId: "siliconflow", modelId: "deepseek-v3-1-terminus", apiModelId: "deepseek-ai/DeepSeek-V3.1-Terminus" },
  { providerId: "siliconflow", modelId: "deepseek-v3-2", apiModelId: "deepseek-ai/DeepSeek-V3.2" },
  { providerId: "siliconflow", modelId: "deepseek-v3-2-exp", apiModelId: "deepseek-ai/DeepSeek-V3.2-Exp" },
  { providerId: "siliconflow", modelId: "deepseek-v4-flash", apiModelId: "deepseek-ai/DeepSeek-V4-Flash" },
  { providerId: "siliconflow", modelId: "deepseek-v4-pro", apiModelId: "deepseek-ai/DeepSeek-V4-Pro" },
  { providerId: "siliconflow", modelId: "ernie-4-5-300b-a47b", apiModelId: "baidu/ERNIE-4.5-300B-A47B", name: "baidu/ERNIE-4.5-300B-A47B" },
  { providerId: "siliconflow", modelId: "gemma-4-26b-a4b-it", apiModelId: "google/gemma-4-26B-A4B-it" },
  { providerId: "siliconflow", modelId: "gemma-4-31b-it", apiModelId: "google/gemma-4-31B-it" },
  { providerId: "siliconflow", modelId: "glm-4-5-air", apiModelId: "zai-org/GLM-4.5-Air" },
  { providerId: "siliconflow", modelId: "glm-5", apiModelId: "zai-org/GLM-5" },
  { providerId: "siliconflow", modelId: "glm-5-1", apiModelId: "zai-org/GLM-5.1" },
  { providerId: "siliconflow", modelId: "glm-5-2", apiModelId: "zai-org/GLM-5.2" },
  { providerId: "siliconflow", modelId: "glm-5v-turbo", apiModelId: "zai-org/GLM-5V-Turbo" },
  { providerId: "siliconflow", modelId: "gpt-oss-120b", apiModelId: "openai/gpt-oss-120b" },
  { providerId: "siliconflow", modelId: "gpt-oss-20b", apiModelId: "openai/gpt-oss-20b" },
  { providerId: "siliconflow", modelId: "hunyuan-a13b-instruct", apiModelId: "tencent/Hunyuan-A13B-Instruct" },
  { providerId: "siliconflow", modelId: "hy3-preview", apiModelId: "tencent/Hy3-preview" },
  { providerId: "siliconflow", modelId: "kimi-k2-5", apiModelId: "moonshotai/Kimi-K2.5" },
  { providerId: "siliconflow", modelId: "kimi-k2-6", apiModelId: "moonshotai/Kimi-K2.6" },
  { providerId: "siliconflow", modelId: "ling-flash-2-0", apiModelId: "inclusionAI/Ling-flash-2.0", name: "inclusionAI/Ling-flash-2.0" },
  { providerId: "siliconflow", modelId: "minimax-m2-5", apiModelId: "MiniMaxAI/MiniMax-M2.5" },
  { providerId: "siliconflow", modelId: "qwen2-5-72b-instruct", apiModelId: "Qwen/Qwen2.5-72B-Instruct" },
  { providerId: "siliconflow", modelId: "qwen2-5-7b-instruct", apiModelId: "Qwen/Qwen2.5-7B-Instruct" },
  { providerId: "siliconflow", modelId: "qwen3-14b", apiModelId: "Qwen/Qwen3-14B" },
  { providerId: "siliconflow", modelId: "qwen3-235b-a22b", apiModelId: "Qwen/Qwen3-235B-A22B-Thinking-2507" },
  { providerId: "siliconflow", modelId: "qwen3-30b-a3b-instruct", apiModelId: "Qwen/Qwen3-30B-A3B-Instruct-2507" },
  { providerId: "siliconflow", modelId: "qwen3-32b", apiModelId: "Qwen/Qwen3-32B" },
  { providerId: "siliconflow", modelId: "qwen3-5-122b-a10b", apiModelId: "Qwen/Qwen3.5-122B-A10B" },
  { providerId: "siliconflow", modelId: "qwen3-5-27b", apiModelId: "Qwen/Qwen3.5-27B" },
  { providerId: "siliconflow", modelId: "qwen3-5-35b-a3b", apiModelId: "Qwen/Qwen3.5-35B-A3B" },
  { providerId: "siliconflow", modelId: "qwen3-5-397b-a17b", apiModelId: "Qwen/Qwen3.5-397B-A17B" },
  { providerId: "siliconflow", modelId: "qwen3-5-9b", apiModelId: "Qwen/Qwen3.5-9B" },
  { providerId: "siliconflow", modelId: "qwen3-6-27b", apiModelId: "Qwen/Qwen3.6-27B" },
  { providerId: "siliconflow", modelId: "qwen3-6-35b-a3b", apiModelId: "Qwen/Qwen3.6-35B-A3B" },
  { providerId: "siliconflow", modelId: "qwen3-8b", apiModelId: "Qwen/Qwen3-8B" },
  { providerId: "siliconflow", modelId: "qwen3-coder-30b-a3b-instruct", apiModelId: "Qwen/Qwen3-Coder-30B-A3B-Instruct" },
  { providerId: "siliconflow", modelId: "qwen3-coder-480b-a35b-instruct", apiModelId: "Qwen/Qwen3-Coder-480B-A35B-Instruct" },
  { providerId: "siliconflow", modelId: "qwen3-vl-235b-a22b", apiModelId: "Qwen/Qwen3-VL-235B-A22B-Thinking" },
  { providerId: "siliconflow", modelId: "qwen3-vl-235b-a22b-instruct", apiModelId: "Qwen/Qwen3-VL-235B-A22B-Instruct" },
  { providerId: "siliconflow", modelId: "qwen3-vl-30b-a3b", apiModelId: "Qwen/Qwen3-VL-30B-A3B-Thinking" },
  { providerId: "siliconflow", modelId: "qwen3-vl-30b-a3b-instruct", apiModelId: "Qwen/Qwen3-VL-30B-A3B-Instruct" },
  { providerId: "siliconflow", modelId: "qwen3-vl-32b", apiModelId: "Qwen/Qwen3-VL-32B-Thinking", name: "Qwen/Qwen3-VL-32B-Thinking" },
  { providerId: "siliconflow", modelId: "qwen3-vl-32b-instruct", apiModelId: "Qwen/Qwen3-VL-32B-Instruct" },
  { providerId: "siliconflow", modelId: "qwen3-vl-8b-instruct", apiModelId: "Qwen/Qwen3-VL-8B-Instruct" },
  { providerId: "siliconflow", modelId: "seed-oss-36b-instruct", apiModelId: "ByteDance-Seed/Seed-OSS-36B-Instruct" },
  { providerId: "siliconflow", modelId: "step-3-5-flash", apiModelId: "stepfun-ai/Step-3.5-Flash" },
  { providerId: "zhipu", modelId: "cogview-4" },
  { providerId: "zhipu", modelId: "glm-5-2", apiModelId: "glm-5.2" },
  { providerId: "zhipu", modelId: "glm-5-2-fast", apiModelId: "glm-5.2-fast" },
  { providerId: "zhipu", modelId: "glm-image" },
  { providerId: "opencode-go", modelId: "deepseek-v4-flash" },
  { providerId: "opencode-go", modelId: "deepseek-v4-pro" },
  { providerId: "opencode-go", modelId: "glm-5" },
  { providerId: "opencode-go", modelId: "glm-5-1", apiModelId: "glm-5.1" },
  { providerId: "opencode-go", modelId: "glm-5-2", apiModelId: "glm-5.2" },
  { providerId: "opencode-go", modelId: "gpt-5-6-luna", apiModelId: "gpt-5.6-luna" },
  { providerId: "opencode-go", modelId: "grok-4-5", apiModelId: "grok-4.5" },
  { providerId: "opencode-go", modelId: "hy3" },
  { providerId: "opencode-go", modelId: "kimi-k2-5", apiModelId: "kimi-k2.5" },
  { providerId: "opencode-go", modelId: "kimi-k2-6", apiModelId: "kimi-k2.6" },
  { providerId: "opencode-go", modelId: "kimi-k2-7-code", apiModelId: "kimi-k2.7-code" },
  { providerId: "opencode-go", modelId: "kimi-k3" },
  { providerId: "opencode-go", modelId: "mimo-v2-5", apiModelId: "mimo-v2.5" },
  { providerId: "opencode-go", modelId: "mimo-v2-5-pro", apiModelId: "mimo-v2.5-pro" },
  { providerId: "opencode-go", modelId: "mimo-v2-omni" },
  { providerId: "opencode-go", modelId: "mimo-v2-pro" },
  { providerId: "opencode-go", modelId: "minimax-m2-5", apiModelId: "minimax-m2.5" },
  { providerId: "opencode-go", modelId: "minimax-m2-7", apiModelId: "minimax-m2.7" },
  { providerId: "opencode-go", modelId: "minimax-m3" },
  { providerId: "opencode-go", modelId: "qwen3-5-plus", apiModelId: "qwen3.5-plus" },
  { providerId: "opencode-go", modelId: "qwen3-6-plus", apiModelId: "qwen3.6-plus" },
  { providerId: "opencode-go", modelId: "qwen3-7-max", apiModelId: "qwen3.7-max" },
  { providerId: "opencode-go", modelId: "qwen3-7-plus", apiModelId: "qwen3.7-plus" },
  { providerId: "opencode-go", modelId: "qwen3-8-max", apiModelId: "qwen3.8-max" },
];
